version: "3.7"

services:
  aiofauth:
    image: gkama/aiof-auth:latest
    container_name: aiof-auth
    ports:
      - 8001:80
    environment: 
      ASPNETCORE_ENVIRONMENT: Development

  aiofmetadata:
    image: gkama/aiof-metadata:latest
    container_name: aiof-metadata
    ports:
      - 8002:80

  aiofapi:
    image: gkama/aiof-api:latest
    container_name: aiof-api
    depends_on:
      - aiofauth
      - aiofmetadata
    ports:
      - 8000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Metadata:BaseUrl: "http://127.0.0.1:8002/api/"
